### PR TITLE
[WIP] GPS pages

### PR DESCRIPTION
**Pull request by steveoh**
[new GPS pages](https://deploy-preview-823--gis-utah-gov.netlify.com/gps/)

If you add the content, I can make it prettier, and @atribolet can make it coherent.

### CODE REVIEW

**Comment by mheagin** [comment]
I committed the changes to the GPS folder, take a look

**Comment by steveoh** [comment]
will you create a pull request from your branch edits to the gps branch on this repository so everyone can see them?

**Comment by steveoh** [comment]
@ZachBeck and I added some images to spruce up the page. Do you like them? @mheagin or @seanfernandez if you have further ideas/critiques let us know to make the page a bit more visual/interesting.

**Comment by steveoh** [comment]
@mheagin the links and prices for turn aren't in here...

image

**Comment by atribolet** [comment]
Do you need anything from me on this? Just let me know! :)

**Comment by steveoh** [comment]
I don't think so @atribolet. @seanfernandez and @mheagin will need to figure somethign out before we could have something for you.

**Comment by atribolet** [comment]
K! Just keep me posted! I'm happy to help whenever!

**Comment by steveoh** [comment]
@seanfernandez and @mheagin are you ready for this to be live?

**Comment by mheagin** [comment]
Lets do push it out to public

**Comment by steveoh** [comment]
@mheagin do you want to write a blog post to let people know about the other network and to have something for the newsletter?

**Comment by mheagin** [comment]
not sure yet, too many issues and we have an upgrade to turn in a week and half. Better after, then hopefully UI will have online payment for NV

**Pull request merged**
