### PR TITLE
add policy page and new sgid policy content

### PR DESCRIPTION
**Pull request by gregbunce**
this pr will add a new page to the website where staff can post related policy. it will be accessed from the 'about' page under the quick links section.

### CODE REVIEW

**Comment by steveoh** [comment]
I think we could maybe merge what you did with the about quick links idea and this agrc data disclaimer
image

Adding the cc by 4.0 as well

**Comment by gregbunce** [comment]
sure, I like it.  should i remove the "policies" menu item and add the link to the about page?

**Comment by steveoh** [comment]
I would definitely remove the menu item

**Comment by gregbunce** [comment]
i'm on it (this afternoon).

**Comment by gregbunce** [comment]
done.

**Comment by gregbunce** [comment]
i added the cc by4 tag to the sgid polciy page, but i'm not convinced we need it on this specific page.  i would say it fits better on the data pages.  feel free to keep or remove.  i'm fine either way.

**Comment by eneemann** [comment]
Since this seems to be more of a general, public-facing guideline now, do we need a more detailed policy for the internal editors?  To guide things like:
- Where is the official metadata maintained?
- If internal SDE, in which section do the details go?

**Comment by gregbunce** [comment]
@steveoh I'm done making my initial comments.  it looks good.  i made a few minor suggestions in the code.

**Pull request merged**
