### PR TITLE
add link to the National Map

### PR DESCRIPTION
**Pull request by rkelson**
all the 2018 lidar pages need to have this added now that is is available from TNM.

### CODE REVIEW

**Comment by steveoh** [comment]
@rkelson Are you going to update all of them in this pull request?

**Comment by rkelson** [comment]
possibly but I can't figure it out for the one page

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by steveoh** [comment]
I can help you figure it out at some point but if you want to try to pick it out from the other pages that already have it, https://github.com/agrc/gis.utah.gov/blob/master/data/elevation-and-terrain/2016-lidar-monroe-mtn/index.md#L17-L19 is an example that I think shows what you want.

**Comment by steveoh** [comment]
nice job

**Comment by steveoh** [comment]
leave me a comment when you have them all in there and i'll merge this

**Comment by rkelson** [comment]
The deploy never seemed to finish so I have not had a chance to review but the edits should be correct now

**Pull request merged**
