### PR TITLE
add thinking beyond the map blogpost

### PR DESCRIPTION
**Pull request by gregbunce**
blogpost based on march 2020 nsgic presentation

### CODE REVIEW

**Comment by gregbunce** [comment]
initial draft pr to check layout, formatting, etc..

**Comment by gregbunce** [comment]
this pr is ready for a review.  no rush, though - it's been on my list since march (nsgic presentation).  it's been through Anna's editing - and this version reflects those suggested changes. 

@steveoh i'm struggling with how to center the image source numbering (line 18, 31, etc).  i tried a few things, but it doesn't look great.  any suggestions?  i think it would look better if the numbers were centered under the image.  but.. it's not the end of the world.   thx!

**Comment by steveoh** [comment]
I'll take a look at this tomorrow.

**Comment by gregbunce** [comment]
great, again.. no rush at all.  thx

**Comment by gregbunce** [comment]
great, thanks.  I reached out to @atribolet on those suggested changes.

**Comment by atribolet** [comment]
> i'm ok with this now. I think the info graphic could use some love.
> 
> * the partial gray border seems odd- **Not sure about the partial gray border? I didn't add that.** 
> * the title is hard to read because it's thin and the image behind is too sharp- **Removed the image; made text larger and more spaced out.** 
> * the paragraph text is hard to read since it is small and blurry- **The paragraph text was previously 18 pt at the top, and 17 and 14 at the bottom, but I upped them to 20,22, and 18 respectively. I also increased the letter spacing. Maybe part of this issue is the way the graphic loaded in the article or something? I also had to change a couple of the icons at the bottom, and reorganize things a bit overall, to make it all fit.** 
> * the orange blocks break GitHub into two word which is weird and annotates only the open sgid. I think some of the branding is off as we don't really call the AGRC Web API AGRC's API, etc.**-GitHub as two words fixed (was just a spacing issue). AGRC's API changed to AGRC Web API. Also changed the orange boxes to white and changed the text color to try to make the contrast more agreeable.**

Revised graphic here: https://drive.google.com/file/d/1QXgJO5UDZZNctVoXTSrq3B6r8ueVpfpS/view?usp=sharing I'll let you two add it back in if you don't mind. @steveoh @gregbunce Or if you need other additional changes in the revised version, let me know.

**Comment by gregbunce** [comment]
great, thanks Anna! It looks good to me.  I'll add it the page and see how it looks.

**Comment by gregbunce** [comment]
it looks good to me.  see what you think, @atribolet @steveoh  : https://deploy-preview-1447--gis-utah-gov.netlify.app/thinking-beyond-the-map/

**Comment by gregbunce** [comment]
actually, i'm going to make one other quick change (not related to the infographic).  so you're good to check that out.  i want to rename one of the links to match the new image... AGRC Web API (that was my bad on the original wording)

**Comment by gregbunce** [comment]
okay, it has my approval for a merge.

**Comment by steveoh** [comment]
Looks awesome!

**Pull request merged**
