### PR TITLE
update Moth page - add 2022 info

### PR DESCRIPTION
**Pull request by gregbunce**
let's preview it

### CODE REVIEW

**Comment by jacobdadams** [comment]
Looks like a file name issue. Let's see how this latest commit deploys.

**Comment by gregbunce** [comment]
bingo!  nice work.  silly casing. thank you!

**Comment by gregbunce** [comment]
i'd say it's ready for a review then merge.

**Comment by jacobdadams** [comment]
My OCD soul wants to resize it to match the others. give me a moment.

**Comment by gregbunce** [comment]
yes, good catch.  i'm on it

**Comment by gregbunce** [comment]
oh, never mind... it's all you.

**Comment by gregbunce** [comment]
give me sec and i'll see what i can do.

**Comment by gregbunce** [comment]
i don't think my adjustment did much, but, oh well.  I'm happy with it.

**Comment by jacobdadams** [comment]
Sounds good to me. I can't approve; you'll need to add me as a reviewer.

**Comment by gregbunce** [comment]
thanks for your assistance on this one @jacobdadams

**Review by stdavis — APPROVED** [review]

**Pull request merged**
