### PR TITLE
Create new post for end of year Muni bndy update

### PR DESCRIPTION
**Pull request by mheagin**
Pull request description
------------------------
post to talk about updates through the end of the year and quick summary of the year.

### CODE REVIEW

**Comment by mheagin** [comment]
Thanks Steve.  
Does this go in the updates on the page automatically or do I need to add in the new link?

**Comment by steveoh** [comment]
I just noticed that the file was placed in `_posts/_posts/2016-12-30-end-of-year-fourth-quarter-updates-for-municipal-boundaries.md` so that is why it hasn't shown up. 

By default it will show up in [News](https://gis.utah.gov/news/). If you want it to show up on the front page, then you will need to add the post to the `Featured` category at the top of the post.

```yaml
categories:
- Featured
```

image

**Comment by mheagin** [comment]
yes it is a post or news that's what I wanted then just put that link in the updated part with the current date.
I am also adding a new section for the Metro Townships, to the Boundaries page so I will add the link then, today hopefully.

**Comment by steveoh** [comment]
i featured the post as well as put the date in the title. check it out and let me know if you want to make any other changes.

**Comment by mheagin** [comment]
Look great.  thanks

**Pull request merged**
