### PR TITLE
chore: remove outdated instruction page

### PR DESCRIPTION
**Pull request by steveoh**
refs #1774

### CODE REVIEW

**Comment by jacobdadams** [comment]
I'll leave it to @gregbunce to make the final call because I don't know anything about the history of the page, whether it needs updating or removal.

**Comment by steveoh** [comment]
Seems to be all Bert and Marc related. I'm fine letting Greg choose.

**Comment by steveoh** [comment]
@gregbunce or @jacobdadams what's the status of this?

**Comment by gregbunce** [comment]
go ahead and remove it.  i have no invested interest in that page.  long, long ago I used it as a basis to build the current configuration of the network dataset build but is no longer needed.  it's old hat.

**Review by gregbunce — APPROVED** [review]

**Pull request merged**
