### PR TITLE
add road update dec2023

### PR DESCRIPTION
**Pull request by gregbunce**
Here are a few new addresses from this road update:

- 1007 E SPRINGWATER WAY Eagle Mountain 84005

- 3212 S ENDLESS TRAIL Hurricane 84737

- 240 W 690 N Logan 84321

### CODE REVIEW

**Comment by gregbunce** [comment]
looks good to me.  let me know if i missed anything, else, please approve but not merge.  i'll merge it later today.  thanks!

**Comment by stdavis** [comment]
I was able to verify "1007 E SPRINGWATER WAY Eagle Mountain 84005", but "3212 S ENDLESS TRAIL Hurricane 84737" returned no matches (perhaps there's still an update that needs to happen?).

Also, whats a house number for "W 690 N Logan 84321" ?

**Comment by gregbunce** [comment]
good catch on the house number, scott.  i added it to the addresses above (240 W 690 N Logan 84321)

yeah, i don't expect the addresses to code yet until road grinder gets updated (probably monday or tues of next week).  

i bet you were able to hit the one address is b/c it's hitting an address point (?).  the address point may have made it into the data (and therefore the locator data) before it made into the roads data.

**Review by stdavis — APPROVED** [review]

**Comment by steveoh** [comment]
All these addresses returned 100 today

**Pull request merged**
