### PR TITLE
Update index.html text to provide additional data description.

### PR DESCRIPTION
**Pull request by clancyblack**
Added some text to describe the geo-location projection to help users map the data after downloading.

Pull request description
------------------------

### CODE REVIEW

**Comment by stdavis** [comment]
Thanks for your contribution!

🎉  on your first pull request!!!

**Comment by clancyblack** [comment]
Not sure if this is monitored. When does the pull request actually hit the
page? Is there another step I need to take? Thanks for your help, this is
my first time doing this.

Clancy

WCEC Engineers
UDOT Consultant
801-722-9736

**Comment by clancyblack** [comment]
Nevermind, I see the change now. Thanks!

WCEC Engineers
UDOT Consultant
801-722-9736

**Comment by stdavis** [comment]
Yep, you got it. The site is automatically rebuilt and published as soon as the pull request is accepted. It usually takes a few minutes for this to happen.

Thanks, again!

**Pull request merged**
