### PR TITLE
Product pillar revisions

### PR DESCRIPTION
**Pull request by jacobdadams**
Review of the products pages (except data pages). I'd especially like @seanfernandez and @DenisePeterson to look over the TURN edits to make sure I'm using `CORS`, etc properly.

### CODE REVIEW

**Review by steveoh — APPROVED** [review]

**Comment by seanfernandez** [comment]
It would sound better if you removed this completely from the products page. "Continuously Operating Reference System (CORS)"

**Comment by jacobdadams** [comment]
What would you change it to, just "reference system"? Because, unless my understanding of GNSS is flawed, GNSS refers to the satellite constellation, ground stations, and receivers, and a reference system like TURN or WAAS are methods to enhance the existing GNSS.

**Comment by seanfernandez** [comment]
In our industry GNSS is like saying GPS except it is referring to a system that uses all available constellation of satellites (USA, Russia, China, Japan, UK) rather than just US satellites. When CORS is used by surveyors it is usually specific to the CORS Network managed by the NGS. 
So it makes sense to use GNSS in place of GPS in this sentence. We originally used GPS because that was the only constellation that was available through our system for a long time, but we have recently upgraded a good portion of the network to provide a full GNSS solution. With that said I don't think we need to go back through everything that mentions GPS and change it to GNSS at this point, but maybe in the future when we are fully integrated.

The Utah Reference Network (TURN) is a high-precision global navigation satellite system (GNSS) network providing real-time corrections and data for post processing. Our network consists of permanently located GNSS receivers installed across Utah and portions of Idaho, Wyoming, and southern Nevada that generate real-time, high-accuracy GNSS positioning. These receivers send their data using the Networked Transport of RTCM via Internet Protocol (NTRIP) to a central system that analyzes the input to adjust and correct the data to provide the most accurate locations, usually down to centimeter level precision. Our network uses the Trimble Pivot VRS Platform.

**Comment by jacobdadams** [comment]
I guess where I'm getting hung up is that by calling TURN a GNSS, to me it
implies that it has it's own constellation, ground stations, receivers,
etc. Maybe this is splitting hairs. I'd really like to call it a GNSS
reference network as a more generic way of saying CORS.

**Comment by steveoh** [comment]
FYI This has  been merged so any new changes will need to be done in a new branch.

**Comment by seanfernandez** [comment]
It is fine for now.

**Pull request merged**
