### PR TITLE
feat: use new data icons

### PR DESCRIPTION
**Pull request by steveoh**
[icon page link](https://deploy-preview-1224--gis-utah-gov.netlify.com/#data)

leftover items

- [ ] I would like to place a link to open data in the top
- [x] Use zach's new above the fold image

### CODE REVIEW

**Comment by gregbunce** [comment]
so are we going live on the website with these?  if so, will they be replaced throughout the site?  aka, on pages such as https://deploy-preview-1224--gis-utah-gov.netlify.com/data/ ?

**Comment by steveoh** [comment]
@gregbunce eventually. This is only a draft to see how they look. We need the complete set and yes they would replace all areas where the old ones were previously used.

**Comment by gregbunce** [comment]
k.  got it!  thx

**Comment by gregbunce** [comment]
i'm suddenly getting nostalgic about the existing images - not that they should stay.  just saying.

**Comment by gregbunce** [comment]
i guess my general feeling is that the icons are 'okay'.  i don't hate them and i don't love them.  i guess seeing them on the website, they look boring.  have we ruled out the jazzier icons that are used on the [LA hub site](http://geohub.lacity.org/)?  also, i do realize that i have done zero work on this project so i don't have much room to bark.   this is just my two cents.

**Comment by steveoh** [comment]
you're fired

**Comment by nathankota** [comment]
Would it make sense to share this pr with Tommy so he can see the issues and hopefully determine the needed icon font and size changes?

**Comment by steveoh** [comment]
I was hoping you would do something like that yes

**Comment by nathankota** [comment]
done

**Comment by ZachBeck** [comment]
@steveoh, I guess I don't understand what you mean in the rectangle example. Are you saying the icons  should be the same size/ratio as the second image?

**Comment by steveoh** [comment]
Since I'm using the svg's instead of the pngs, there are some oddities. If you look at this image

**Comment by nathankota** [comment]
There's a new svg to test out: 
image

For the remaining icons, how do these abbreviations sound?
911 - the '11' would be smaller
Ad - Address
Ae - Aerial photos
Co - Contours
El - Elevation
In - Indices
To - Topo maps

**Comment by steveoh** [comment]
It's triple the file size since the text is now vectorized. But the overall image size looks better in the quick look.

image

Let's see how it looks in the preview

**Comment by nathankota** [comment]
Sorry, I missed the bottom part of your comment earlier. By using the text element are you saying remove the full category name from the icons, so they only include the abbreviations? I will ask Tommy for an svg to test, and let him know the font family.

**Comment by steveoh** [comment]
No i am not saying to remove text.

The original did this...


```xml
<text transform="translate(582 320)" fill="#fff" font-size="72" font-weight="bold" font-family="Open Sans,Helvetica,Arial,sans-serif">
    <tspan x="-34.056" y="0">Bi</tspan>
  </text>
```

The new one does this instead...

```xml
<g xmlns="http://www.w3.org/2000/svg" id="Tr" style="isolation:isolate">
<g style="isolation:isolate">
<path d="M30.63063,22.675h-10.858V13.96559h31.6453V22.675H40.61773V52.69457h-9.9871Z" fill="#fff"/>
<path d="M52.518,24.6492h8.94173v3.542a12.22406,12.22406,0,0,1,8.7677-4.23895v8.65194a7.23843,7.23843,0,0,0-2.20649-.29058c-2.32226,0-5.39969.98749-6.56121,2.61283V52.69457H52.518Z" fill="#fff"/>
</g>
</g>
```

**Comment by nathankota** [comment]
copy that

**Comment by nathankota** [comment]
Tommy's response: "I don't understand the file size concern,  6KB for an image is already really small." 

He sent a new transportation logo using open sans which is in the opendata.gis.utah.gov v1.1 folder on team drive.

**Comment by steveoh** [comment]
The new image looks great. Let's get all of the icons done that way. 

I have no comment to his size concern comment

**Comment by steveoh** [comment]
It looks like I have a bit more work to do to make the font get picked up but I wanted to get them all in there first to see if anyone wanted to recommend modifications

**Comment by steveoh** [comment]
that's the 3rd optimization over the same data...

**Comment by steveoh** [comment]
this is ready for review. @nathankota was thinking we would publish this when the open data site is done so it all goes out together. Let's get this pr sorted out while the final touches go on open data.

**Pull request merged**
