### PR TITLE
fix: link directly to open data

### PR DESCRIPTION
**Pull request by jacobdadams**
Direct link to dataset in open data; remove Lee's email.

### CODE REVIEW

**Review by steveoh — APPROVED** [review]
Did someone request this?

**Comment by jacobdadams** [comment]
> Did someone request this?

Yeah, Lee sent an e-mail to Matt requesting the update. I'm waiting to get his ok on the description text.

**Comment by nathankota** [comment]
Will this also affect the description here? 

image

**Comment by jacobdadams** [comment]
No, that comes from the stewardship doc (more reason for a unified metadata db).

**Review by stdavis — DISMISSED** [review]

**Comment by jacobdadams** [comment]
Lee supplied an updated description, which has been added.

**Comment by steveoh** [comment]
Can you add that to the stewardship sheet as well.

**Review by steveoh — APPROVED** [review]

**Pull request merged**
