### PR TITLE
add link for USFWS wetland mapping services

### PR DESCRIPTION
**Pull request by rkelson**

### CODE REVIEW

**Comment by rkelson** [comment]
this page uses download: not hub:

**Comment by steveoh** [comment]
sorry I meant endpoints.

```yml
item:
  downloads:
    - url: 
      label: 
  updates:
    - 
  endpoints:
    - url: 
      label: 
```

e.g. https://github.com/agrc/gis.utah.gov/blob/master/data/911/index.html#L21-L25

**Comment by rkelson** [comment]
the link is to a page containing multiple endpoint options

**Comment by rkelson** [comment]
let's get this merged and when I have the time I will add endpoints: to this page and fix the Floodplains page https://gis.utah.gov/data/water/flood-areas/

**Comment by steveoh** [comment]
Don't worry, I made time to do it for us.

**Review by steveoh — APPROVED** [review]

**Pull request merged**
