### PR TITLE
Jake demographics- hub download refactor

### PR DESCRIPTION
**Pull request by jacobdadams**
Is this a bad idea? 

I'm trying to eliminate the repetitive task for data pages where it makes sense to have multiple items per page (census year pages, probably h3 as well). 

Having multiple download sections does throw off the striping, which needs to be fixed manually. 

But is this just needlessly complicating the components?

### CODE REVIEW

**Comment by steveoh** [comment]
I think it is a bad idea. It's what we wanted to get away from.

**Comment by jacobdadams** [comment]
Is it worse than having 6 separate pages where the only difference is "Census Blocks" instead of "Census Block Groups", etc?

**Comment by steveoh** [comment]
Yes and no. Duplication obviously is an issue, but consistency and familiarity is what we want to provide. Ideally it's an opportunity to explain the uniqueness of each dataset and why you would choose it. It will create special cases for the MATT which also isn't ideal.

**Comment by jacobdadams** [comment]
Hmm... would it be bad to create custom components for each census' description section (2020, 2010, etc) that could then be imported into that section in each separate data page, so we only had one place for the description text?

**Comment by steveoh** [comment]
That's 💯 fine. There's a partials folder where we do this already.

**Comment by jacobdadams** [comment]
closing and nuking branch in favor of `_partials` workflow

**Pull request closed without merging**
