### PR TITLE
Need note for Creating an Account

### PR DESCRIPTION
**Pull request by mheagin**
Updated instructions for users trying to create a new account.

Pull request description
------------------------

### CODE REVIEW

**Comment by mheagin** [comment]
got those list tags in. thanks

**Comment by stdavis** [comment]
👍

**Comment by mheagin** [comment]
is there  a way to comment out a section and leave it there?
Want to keep the regular way to do the registration, call me an optimist, but maybe better to block it out for now.  Thanks

**Comment by stdavis** [comment]
http://html.com/tags/comment-tag/

e.g.
```html
<!--
<div>stuff that you want to comment out</div>
<ul></ul>
-->

<div>other stuff</div>
```

**Pull request merged**
