### PR TITLE
Mheagin/political districts

### PR DESCRIPTION
**Pull request by steveoh**
Please review the following pages:

- [political index page](https://deploy-preview-1886--gis-utah-gov.netlify.app//data/political/)
- [2002](https://deploy-preview-1886--gis-utah-gov.netlify.app/data/political/2002-2011-house-senate-congressional-districts/)
- [2012](https://deploy-preview-1886--gis-utah-gov.netlify.app/data/political/2012-2021-house-senate-congressional-districts/)
- [2022](https://deploy-preview-1886--gis-utah-gov.netlify.app/data/political/2022-2032-house-senate-congressional-districts/)

### CODE REVIEW

**Comment by steveoh** [comment]
@mheagin - I think once we get the 2022 images this is ready to merge if everything else looks ok.

**Review by mheagin — APPROVED** [review]

**Review by mheagin — APPROVED** [review]
they all look fine  Thanks

**Comment by steveoh** [comment]
we decided to keep the old images because they don't offer much to the page.

**Comment by gregbunce** [comment]
Looks good to me!  Nice work.

**Review by gregbunce — APPROVED** [review]

**Pull request merged**
