### PR TITLE
updating hexagon service date link

### PR DESCRIPTION
**Pull request by jacobdadams**

### CODE REVIEW

**Comment by steveoh** [comment]
Is this a new dataset for open data, the internal sgid, and the cloud sgid?

**Comment by jacobdadams** [comment]
> Is this a new dataset for open data, the internal sgid, and the cloud sgid?

Yeap. I've uploaded it to AGOL, shared w/Open Data, added it to SGID.META.AGOLItems, and (per Scott's request) just added it to SGID10 as well for swapper. Is there anywhere else we need to reference it?

**Comment by steveoh** [comment]
I would suggest the stewardship tab. Rick removed indices from the website so probably not as relevant there unless he decides he wants to bring it back.

**Comment by steveoh** [comment]
are you ready for a merge?

**Pull request merged**
