### PR TITLE
Expand the sharing section of our website

### PR DESCRIPTION
**Pull request by steveoh**
I was trying to expand the sharing from just core layers to open data, our website, the sgid index, and the sgid database. I think some work needs to happen to the core data attribute page from rick. I know greg wanted to make some touch up work there. 

What do you think about using this branch as a spot to make those improvements?

### CODE REVIEW

**Comment by rkelson** [comment]
Oh yes now I see the original image now. Kind of confusing to have the 'sharing' page that is similar to the 'core-date' page but looks like a good WIP

**Comment by steveoh** [comment]
Thanks for the feedback rick. I was hoping you could help me adjust the core data page to be more about the schema and the core data sets. I wanted to capture all of the sharing options that we currently have now with agol and whatever as we didn't have that anywhere. Do you have any thoughts or suggestions? You are welcome to hack and slash on this sharing branch

**Comment by rkelson** [comment]
I'll put it on the list of things to do but I don't have time to contribute
to the page at the moment.

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by gregbunce** [comment]
I committed some minor changes to the road centerlines section of this page https://deploy-preview-1275--gis-utah-gov.netlify.com/sharing/core-data/#road_centerlines
the changes include updating the links to the data model and schema and updating the minimum attributes to scale it down it and use the current schema field names.

**Comment by steveoh** [comment]
@gregbunce do you mind helping me shape the page you edited now that it's not the main landing page. I don't really understand it's purpose myself. It seems that all the folks working on those layers are already on board but maybe there are others we are trying to reach? What say you?

**Comment by gregbunce** [comment]
yup, I'd like to help with this.  can we bump it to next week?

**Comment by steveoh** [comment]
I've been chatting with rick about this and yes next week is good.

**Comment by steveoh** [comment]
@gregbunce what are your thoughts on driving this past the finish line in the next couple of weeks?

**Comment by gregbunce** [comment]
i like it.  i'll schedule some time next week with @rkelson and maybe @jacobdadams to close it out.

**Comment by jacobdadams** [comment]
@gregbunce, I was planning on tackling this as part of the data ingestion process fixes. Are you OK if I take a first stab at it and then bring that to you and Rick for review?

**Comment by rkelson** [comment]
Stab away @jacobdadams

**Comment by gregbunce** [comment]
What do you think about meeting Dec 9th some time during the day?  Too soon?  If so we can set up something for a later date. Thanks again.

**Comment by jacobdadams** [comment]
I can try to have something prepped by then, sure.

**Comment by steveoh** [comment]
@jacobdadams should we close this?

**Comment by steveoh** [comment]
https://github.com/agrc/gis.utah.gov/pull/1627/ has the latest and greatest

**Pull request closed without merging**
