### PR TITLE
Road update nov2022

### PR DESCRIPTION
**Pull request by gregbunce**
WIP - checking if everything looks okay

### CODE REVIEW

**Comment by gregbunce** [comment]
@steveoh here are two new addresses from this road update.  moving forward, i'll add them here in the PR each month.

- 3782 W 50 S; Clearfield, Utah 84015
- 352 N Firerock Way; Hurricane, Utah 84737

**Comment by gregbunce** [comment]
it looks good to me.  let me know if i missed anything.  else, please approve and merge.  thanks!

**Comment by steveoh** [comment]
Thanks for the addresses @gregbunce. The locators will not be updated unless we do it manually until we make progress with our wednesday meeting.

**Review by steveoh — DISMISSED** [review]

**Comment by gregbunce** [comment]
you're welcome.  yup, thanks for the reminder.  

let me know if you want me to remove the locator bit in that sentence.  happy to do it.

**Comment by steveoh** [comment]
up to you. this will merge when you resolve that comment.

**Review by steveoh — APPROVED** [review]

**Pull request merged**
