### PR TITLE
overhaul of elevation-terrain page

### PR DESCRIPTION
**Pull request by rkelson**
add new dem section and remove old dem and ned sections
This page should not be merged until Raster app is updated and a successful forklift

------------------------

### CODE REVIEW

**Comment by rkelson** [comment]
willdo

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by steveoh** [comment]
This looks pretty good. Let me know when you'd like a merge with a comment.

**Comment by rkelson** [comment]
I need to wait until raster is all wired up to serve the new dataset so we
will need to merge next week

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by rkelson** [comment]
ready to merge

**Pull request merged**
