### PR TITLE
[WIP] add contour category

### PR DESCRIPTION
**Pull request by steveoh**
refs #863

Pull request description
------------------------
- [x] Add the contours page to the list of data categories (preferred) OR add to the Elevation and Terrain page
- [ ] Add section for these contours: https://gis.utah.gov/dumbing-down-terrain-with-contour-polygons/
- [ ] Add section for other contour Zach has "Bert made him do it"

### CODE REVIEW

**Comment by rkelson** [comment]
contours added to data categories looks good

**Comment by steveoh** [comment]
Whats up with the other two sections @rkelson

**Comment by rkelson** [comment]
someday WIP


Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by steveoh** [comment]
@rkelson - ok should I merge and close this and your issue then?

**Comment by rkelson** [comment]
can't you merge and leave issue open



Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Pull request merged**
