### PR TITLE
add shortcut to sgid search index

### PR DESCRIPTION
**Pull request by gregbunce**

### CODE REVIEW

**Review by steveoh — CHANGES_REQUESTED** [review]
you duplicated the moth item from 166

**Comment by gregbunce** [comment]
oops, good catch. thanks. fixed.

**Review by steveoh — APPROVED** [review]

**Comment by steveoh** [comment]
where are you using these redirects? They might become technical debt with the page structure redesign is the only reason I ask.

**Comment by gregbunce** [comment]
I'm not hard-coding them anywhere.  it's just easier to remember the redirect.  i wanted to put in the nsgic presentation in case anyone wanted to check it out.  so, it would be me telling folks verbally of the URL.

**Pull request merged**
