### PR TITLE
added new 2019 download link

### PR DESCRIPTION
**Pull request by ZachBeck**
Also removed link to old 2000 gnis. BLM was having difficulty finding 2019 data..

### CODE REVIEW

**Comment by steveoh** [comment]
what about the sgid index and back seat driver?

image

**Comment by ZachBeck** [comment]
I'll remove the 2000 gnis from the index. I'm not sure how to update backseat driver.

**Comment by steveoh** [comment]
Are planning to keep this type of historical data somewhere for some future analysis? What did your group decide?

**Comment by steveoh** [comment]
@stdavis do you mind checking backseat driver for the 1990 and 2000 GNIS entries?

**Comment by ZachBeck** [comment]
No decision on the historical stuff yet. I don't know if there is any value in 19 year old gnis.

**Comment by steveoh** [comment]
what about the 1990 gnis that is available in the index? 

I could see change over time being mildly interesting but I also agree with you.

**Comment by stdavis** [comment]
Here's the removal of old GNIS data from backseat driver: https://github.com/agrc/backseat-driver/pull/33

@ZachBeck Would you please submit a PR to the backseat driver repo with your config for the 2019 data? Just so that we keep all of the configs in the same place.

**Comment by ZachBeck** [comment]
On second thought @stdavis hold off. This is becoming a lesson in deprecating/archiving data and naming conventions. There will be some other changes coming.

**Comment by steveoh** [comment]
it's been a week. what needs to happen before merging this?

**Comment by ZachBeck** [comment]
I think it can be merged now. It's good now for the time being but there will be other changes coming. I have copies of the 1990 and 2000 gnis that can be moved into AGOL when an archive area is set up.

**Pull request merged**
