### PR TITLE
Add New Demographics Projections web page

### PR DESCRIPTION
**Pull request by bertgranberg**
This page probably needs a little more work but I've gotten it as far as I care to without being able to preview the page. Hopefully this is a decent start and you can help me take it from here to polished. (Thanks!)

Basic idea is that there are four categories of datasets:

- Population & Household Projections @ CityArea polygon geography
- Population & Household Projections @ Traffic Analysis Zone polygon geography

- Employment Projections @ CityArea polygon geography
- Employment Projections @ Traffic Analysis Zone polygon geography

Follow up activities include 
1) Adding Anchors tags to each of the above categories on the page
2) Adding a link to these 4 datasets (and their anchors) from the SGID Demographics index page
3) Possibly adding GPI to your contacts data structure. 
4) Adding a county level projections and estimates page (I'll have to coordinate with GPI on this so this is probably a month or two down the road but getting this page up may inspire them to participate sooner/faster)

### CODE REVIEW

**Comment by steveoh** [comment]
You are able to preview the page as long as it was built. 


https://deploy-preview-1233--gis-utah-gov.netlify.com/

**Comment by bertgranberg** [comment]
Hmmm...made some progress on this...the latest deployment seems to have some failing issues? Can you advise?

**Comment by steveoh** [comment]
Sure I’ll look at it this evening to get you back previewing

**Comment by steveoh** [comment]
If you look at the [log](https://app.netlify.com/sites/gis-utah-gov/deploys/5d963753f8e3b10008842219) it shows invalid syntax. I’d assume it is because you nested double quotes on a link. For now I would remove the html syntax  to get your previews working again and I can fix the link later for you.

**Comment by steveoh** [comment]
@bertgranberg This looks good to me. I'm happy to merge this after these `<a href="metadataURL">See open data page for metadata</a>` meta data links are populated or removed since they aren't really valid links.

**Comment by bertgranberg** [comment]
> @bertgranberg This looks good to me. I'm happy to merge this after these `<a href="metadataURL">See open data page for metadata</a>` meta data links are populated or removed since they aren't really valid links.

I removed the links...hope that works

**Pull request merged**
