### PR TITLE
Parcel page edits

### PR DESCRIPTION
**Pull request by rkelson**
add link to land ownership page
add note that address points are authoritative

### CODE REVIEW

**Comment by steveoh** [comment]
```Liquid Exception: Invalid syntax for include tag: name="Utah Parcel Data" stewards="AGRC and Local Government" webapp="https://parcels.utah.gov" abstract="Parcel data contains GIS mapping data representing parcel boundaries. AGRC has parcel data for all 29 counties. Some counties are more complete than others. In addition to the polygon geometry the attributes <code>PARCEL ID</code>, <code>PARCEL ADDRESS</code>, <code>PARCELS CITY</code>, <code>PARCEL ZIP CODE</code>, <code>OWNERSHIP TYPE</code>, and <code>RECORDER</code> contact are maintained in the Basic Parcel dataset when available. Users should be aware the owner type field <code>OWN_TYPE</code> in the parcel polygons is a very generalized ownership type (Federal, Private, State, Tribal). It is populated with the value of the <code>OWNER</code> field where the parcel's centroid intersects the <a href="{% link data/cadastre/land-ownership/index.html Valid syntax: {% include file.ext param='value' param2='value' %} in data/cadastre/parcels/index.html```

**Comment by steveoh** [comment]
still have """" which isn't valid. switch them to singles or escape them

**Comment by rkelson** [comment]
I don't see where the issue is

**Comment by steveoh** [comment]
abstract is a string so it boils down to

```
abstract=""
```

you've got 

```
abstract="Parcel data contains GIS mapping data representing parcel boundaries. AGRC has parcel data for all 29 counties. Some counties are more complete than others. In addition to the polygon geometry the attributes <code>PARCEL ID</code>, <code>PARCEL ADDRESS</code>, <code>PARCELS CITY</code>, <code>PARCEL ZIP CODE</code>, <code>OWNERSHIP TYPE</code>, and <code>RECORDER</code> contact are maintained in the Basic Parcel dataset when available. Users should be aware the owner type field <code>OWN_TYPE</code> in the parcel polygons is a very generalized ownership type (Federal, Private, State, Tribal). It is populated with the value of the <code>OWNER</code> field where the parcel's centroid intersects the <a href="{% link data/cadastre/land-ownership/index.html %}">Land Ownership</a> polygon layer." %}
```

`<a href="{% link data/cadastre/land-ownership/index.html %}">` adds double quotes inside double quotes which is invalid.

**Comment by rkelson** [comment]
bummer

**Comment by steveoh** [comment]
Yes like that but inside the abstract="" part so the other link

**Review by steveoh — APPROVED** [review]

**Pull request merged**
