### PR TITLE
clean up and validate html

### PR DESCRIPTION
**Pull request by stdavis**
Pull request description
------------------------

### CODE REVIEW

**Comment by steveoh** [comment]
I would also like to rename this folder from `sgid-transportation` to `transportation`. We will need to update the [_redirects](https://github.com/agrc/gis.utah.gov/blob/bfa0e7891d0f43851110f348e7855967682e56a5/_redirects) similar to how it was done with the `society-overview` -> `society` rename

**Comment by stdavis** [comment]
> I would prefer 2 space indent on html but it's not breaker.

I think that it a bit jarring to have html at 2 spaces and other code at 4 spaces but it's not a huge deal to me. I'd like to be consistent however we decide to go. Maybe this is a good case for tabs. Then each user could configure the length to their liking.

**Comment by stdavis** [comment]
> add the overview tag and remove data

Is there a list of acceptable tags anywhere?

**Comment by stdavis** [comment]
OK. I think that I have this cleaned up...

**Pull request merged**
