### PR TITLE
change DRG ftp links to GCS - 100K

### PR DESCRIPTION
**Pull request by rkelson**

### CODE REVIEW

**Comment by stdavis** [comment]
I think that you're links should be more like this: https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/24k/Collarless/q1217_DRG24k-c.zip, shouldn't they? As they are currently in this PR, they don't work for me.

**Comment by rkelson** [comment]
oh yes you are right

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov

**Comment by stdavis** [comment]
These links are broken on data/usgs-scanned-topographic-maps/1-to-100000/index.html:

 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5119_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9527_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4735_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5095_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5103_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9511_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4727_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9519_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4743_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9503_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4695_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5135_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5143_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4711_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9495_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5111_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4719_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9535_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5127_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9543_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5119_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9527_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9519_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5095_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4727_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5103_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4735_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4703_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4743_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9511_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9503_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4695_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5143_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5135_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4711_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9535_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9543_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q4719_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q9495_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5111_DRG100K-c.zip
 https://storage.googleapis.com/state-of-utah-sgid-downloads/drgs/100k/Collarless/q5127_DRG100K-c.zip
 https://storage.googleapis.com/state-of-uta

**Comment by steveoh** [comment]
it looks like these links are broken on the page now. I'll call this an improvement and we can remove the extra quads that don't exist. There should only be 84 or so items and this page has 107

**Pull request merged**
