### PR TITLE
GOED Rec Grants Image

### PR DESCRIPTION
**Pull request by jpechmann**
New cover photo.

Pull request description
------------------------

### CODE REVIEW

**Comment by jpechmann** [comment]
Good catch @steveoh. It does matter and was the right orientation on my computer.

**Comment by steveoh** [comment]
would you like me to accept it as is or are you going to update it?

**Comment by jpechmann** [comment]
I'm going to try to fix it.

**Comment by steveoh** [comment]
just commit it here, not need to close it.

**Comment by jpechmann** [comment]
@steveoh okay I fixed it! thank you!

**Pull request merged**
