### PR TITLE
feat: moth 2024

### PR DESCRIPTION
**Pull request by jacobdadams**
Adding MOTH 2024 to the page (plus some `prettier` auto-formatting?)

### CODE REVIEW

**Review by steveoh — CHANGES_REQUESTED** [review]
This repo doesn't use prettier and those changes appear to have broken the page. Can you undo the edits and disable prettier or save without formatting?

**Comment by jacobdadams** [comment]
> This repo doesn't use prettier and those changes appear to have broken the page. Can you undo the edits and disable prettier or save without formatting?

Yeah, I saw that and I'm trying to clean it. 

Is the new website using prettier? I thought I saw it in the recommended extensions...

**Comment by jacobdadams** [comment]
K, I think I fixed it. It was moving the `{: .dotless .no-padding}` out of alignment.

**Comment by steveoh** [comment]
> > This repo doesn't use prettier and those changes appear to have broken the page. Can you undo the edits and disable prettier or save without formatting?
> Is the new website using prettier? I thought I saw it in the recommended extensions...

Yes the astro version of the website is using prettier.

**Review by steveoh — APPROVED** [review]

**Pull request merged**
