### PR TITLE
Geoscience changes

### PR DESCRIPTION
**Pull request by brigsz**
Pull request description
------------------------
Addition of Earthquakes and also Geochronology links and sub pages

### CODE REVIEW

**Comment by steveoh** [comment]
change the title and leave a comment when you are ready for this to be merged!

**Comment by steveoh** [comment]
Great effort so far @brigsz 🎆 🎉 🎊 

Things left to do for geochronology to be acceptable

- [ ] buff abstract name
- [ ] update individual package images
- [ ] update package image
- [ ] update package content

**Comment by brigsz** [comment]
I believe I am closer than before and am now ready to update the package content?  Not sure what that is, or is that the actual files on the AGRC google drive?

**Comment by steveoh** [comment]
@brigsz, Will you send the data or feature class names in the SGID to @keatonwalker so he can get that going?

**Comment by brigsz** [comment]
@steveoh , yes, I believe Zach and Keaton are already working on it.  We had a hangout today Nov 27th in the morning and discussed it. I will follow up with them now

**Comment by steveoh** [comment]
is this done @brigsz

**Comment by brigsz** [comment]
I think it is, but really the links should be checked on Earthquakes links

On Nov 28, 2017, at 6:11 PM, steveoh <notifications@github.com> wrote:

is this done @brigsz <https://github.com/brigsz>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/gis.utah.gov/pull/678#issuecomment-347718962>, or mute
the thread

**Comment by steveoh** [comment]
Argon and lab links are all fouled up.

**Comment by brigsz** [comment]
Okay, I will get on that.

On Nov 28, 2017, at 7:10 PM, steveoh <notifications@github.com> wrote:

Argon and lab links are all fouled up.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/gis.utah.gov/pull/678#issuecomment-347729400>, or mute
the thread

**Pull request closed without merging**
