### PR TITLE
add jake's twitter

### PR DESCRIPTION
**Pull request by gregbunce**

### CODE REVIEW

**Comment by steveoh** [comment]
Is this something you want @jacobdadams?

**Comment by jacobdadams** [comment]
Oh noes! The secret is out! :)

Go ahead, I'd forgotten to add this when I got my Twitter game/flamesuit on a couple weeks ago.

**Comment by steveoh** [comment]
a couple of weeks ago... riiiiight 

> Joined July 2015

**Comment by jacobdadams** [comment]
Just check the date of the first tweet 😉

**Comment by steveoh** [comment]
ok i know this wasn't a competition but you win! 🏁

**Pull request merged**
