### PR TITLE
Use hub connection for land ownership

### PR DESCRIPTION
**Pull request by steveoh**
image

The first link will not work until the sharing is setup with our hub.
The second and third link do download but I'm unsure if it's accurate?

### CODE REVIEW

**Comment by gregbunce** [comment]
I have verified that the currently available e as downloadable is accurate.

I'm reaching out to SITLA now for open data sharing via agol.

**Comment by steveoh** [comment]
> I have verified that the currently available, downloadable data on our data page is accurate.
> 
> I'm reaching out to SITLA now for open data sharing via agol.

Did you look at the output from this pull request or what is on the prod website?

**Comment by gregbunce** [comment]
good catch.  i corrected it.  thanks!

**Comment by gregbunce** [comment]
okay, she shared the [newest land ownership layer](https://opendata.gis.utah.gov/datasets/SITLA::land-ownership/explore) with us.

should we do a draft PR to see if it wires up?

**Comment by gregbunce** [comment]
nevermind.  ha.  this is a pr

**Comment by gregbunce** [comment]
url and downloads are now working.  

ready to be merged, aye?

**Pull request merged**
