### PR TITLE
cooling tower update blog post

### PR DESCRIPTION
**Pull request by eneemann**
Here's my update blog post for the cooling towers project.  Let me know what you think.  No big rush, I estimated July 5th as a date, but that can be changed.  It's been a while, so hopefully I'm doing this right 😉.  @nathankota maybe run it by the DHHS folks or think about it from their perspective?

### CODE REVIEW

**Review by stdavis — APPROVED** [review]
Hey stranger! This looks great to me. I hope all is well at the new job.

**Comment by eneemann** [comment]
Hey @stdavis!  I can't see the preview of my blog post, so I tried to change the data to today in the markdown, but it only added the commit to my fork.  Can I add that commit to this PR?  I don't see where to do that.

**Comment by stdavis** [comment]
That new commit on your fork should have shown up in this PR. I'm not sure what's going on. When I go to edit the file from my end, it shows the updated date of 6/30. I would let it sit for a bit and see if it works itself out.

**Comment by eneemann** [comment]
Okay, that's what I thought, but it didn't seem to get associated with the PR. 🤷‍♂️

**Comment by stdavis** [comment]
Ya, maybe @steveoh has an idea but I'm not sure what happened. You might want to try just opening a new PR. I'm happy to do that for you if you would like.

**Comment by eneemann** [comment]
Will reopen a new PR to get the latest commit.

**Pull request closed without merging**
