### PR TITLE
fix: make download links more apparent

### PR DESCRIPTION
**Pull request by stdavis**
Also removed links to iron, carbon and washington county websites/maps since they are broken or not publicly accessible.

### CODE REVIEW

**Comment by stdavis** [comment]
Preview page: https://deploy-preview-1680--gis-utah-gov.netlify.app/data/cadastre/parcels/

**Review by steveoh — APPROVED** [review]

**Comment by eneemann** [comment]
I think this PR looks good and accomplishes the desired effect.  For Washington county, I think they changed the URL for their webmap, so we could use the new one (https://geoprodvm.washco.utah.gov/Html5Viewer/?viewer=WashingtonCounty).  It's a generic web map and takes a few click to get to parcels, but I think it would replace what we had before.

**Review by eneemann — APPROVED** [review]
I don't know if I have the authority, but I'm going to approve this.  Thanks for adding the WashCo link @stdavis. I wasn't sure if I should just do it or if the PR was about to be merged.

**Comment by stdavis** [comment]
Thanks for the review, @eneemann! I'm going to wait until I get thoughts from @rkelson on this since this seems to be his territory...

**Comment by rkelson** [comment]
I could go with this but it's a little early on a Monday to commit to this PR. Let me think about it for a bit

**Review by rkelson — APPROVED** [review]
looks like a masterpiece. I approve of this message um PR

**Pull request merged**
