### PR TITLE
Updated Nevada GPS page

### PR DESCRIPTION
**Pull request by atribolet**
(I'm sure I've messed up the formatting on this, but I'll create a change request and work on it more!)

Pull request description
------------------------

### CODE REVIEW

**Comment by atribolet** [comment]
@mheagin K, I've started the pull request and added in the changes, but I'm sure the formatting is way off right now! If I can't fix it, maybe you can take a look at it, @steveoh? Thanks!

**Comment by atribolet** [comment]
K, @mheagin, I think I've got the formatting fixed (but let me know if you see anything that's still off!). Also, is this line in the right place? "The Nevada GPS Network (formerly Washoe County GPS Network) is now being managed by the State of Utah. "?

**Comment by atribolet** [comment]
Great! Well, @steveoh if you see anything else, please feel free to fix it, but otherwise, could you please publish this? :) Thanks!!

**Comment by steveoh** [comment]
you need to update the title to remove the work in progress still ;)

**Pull request merged**
