### PR TITLE
[WIP] Embed UtahMunicipalBoundaries Open Data Page - Landscape

### PR DESCRIPTION
**Pull request by stdavis**

### CODE REVIEW

**Comment by steveoh** [comment]
This looks decent. I do not like the header from the open data page. I think we should hide that and place move the link to the open data page to that spot or also remove it. I would also be curious to see how the page looks with the text above the map if that is possible.

**Comment by steveoh** [comment]
I spoke with some open data folks and decided this was not a great/supported idea.

If we want to add previews, we should create a plugin for jekyll and use arcgis online web map id's or feature layer id's to generate a map preview.

**Comment by brigsz** [comment]
Mmmmmm, it is more than just a map preview, more a link to all the other information, like attributes etc. and the other functionality

**Comment by stdavis** [comment]
> I spoke with some open data folks and decided this was not a great/supported idea.

Because design changes on their end breaks our layout? I can see that.

**Comment by steveoh** [comment]
It sounded like we were using an old version of open data and it wasn't supported yet in the new version. I thought it was just for preview so adding a map was the obvious solution

**Comment by steveoh** [comment]
I think we need to wait and see what happens with our open data v2 upgrade. I'm going to close this for now since this is going to be different from v2.

**Pull request closed without merging**
