### PR TITLE
add sgid logo

### PR DESCRIPTION
**Pull request by gregbunce**
playing around with adding the sgid logo to the data page.  

input and/or tinkering welcome.

### CODE REVIEW

**Comment by gregbunce** [comment]
@steveoh no rush on this.  when you get time, see what you think.

**Comment by gregbunce** [comment]
the biggest issue i see is that we have conflicting usage of SGID on the page (database and datasource in the logo).   either we change the text on the page or change the text on the logo.  thoughts?

**Comment by jacobdadams** [comment]
I know I'm not a reviewer on this, but the logo doesn't seem like it fits/flows well with the page. Maybe it needs to be smaller? I think those category quick links should always be at the top of the page.

**Comment by gregbunce** [comment]
you're a reviewer now, @jacobdadams thanks for the feedback

**Comment by gregbunce** [comment]
maybe it goes directly below the category images

**Comment by steveoh** [comment]
image

Looks pretty bad on mobile

**Comment by gregbunce** [comment]
take another look and see what you think.

**Comment by steveoh** [comment]
It looks way better

**Comment by gregbunce** [comment]
What do all think about the placement on the page?  Feel free to move it around to see if there's a better spot.  Personally, I kind of like it right there but have at it.

**Review by jacobdadams — APPROVED** [review]

**Pull request merged**
