### PR TITLE
add interactive map link to post

### PR DESCRIPTION
**Pull request by gregbunce**
folks have asked for a link to app. the embedded map on the page is not great on mobile.

### CODE REVIEW

**Review by stdavis — APPROVED** [review]

**Comment by steveoh** [comment]
What's up on mobile? Is there some css or otherwise to make it more useful?

**Comment by gregbunce** [comment]
Sounds like navigating is tough, but the main thing is the legend takes over the map.

**Comment by steveoh** [comment]
Should we hide it on small screens?

**Comment by gregbunce** [comment]
Yeah, that would be great if it's possible.

**Pull request merged**
