### PR TITLE
update parcel page documentation

### PR DESCRIPTION
**Pull request by rkelson**
change state code reference numbers
link to state code page
this was pointed out by the state auditors office. they found it while working on some new administrative rule

### CODE REVIEW

**Comment by rkelson** [comment]
salt lake county parcels just showed up if you would like to hold off merging this until I get the parcels processed

**Review by steveoh — APPROVED** [review]

**Comment by steveoh** [comment]
whoops. didn't read the comment. make it a draft please if you want to hold off.

**Comment by rkelson** [comment]
yes I should have reverted to draft

**Comment by steveoh** [comment]
I should have read the comment :)

**Pull request merged**
