### PR TITLE
Road update april2021

### PR DESCRIPTION
**Pull request by gregbunce**

### CODE REVIEW

**Comment by gregbunce** [comment]
just checking things out...

**Comment by gregbunce** [comment]
@stdavis feel free to approve these changes if they look good to you but, i'll wait to merge it until the data goes live in open data.  i'm happy to do the merge when that happens.

**Review by stdavis — DISMISSED** [review]

**Comment by steveoh** [comment]
we should update the dates, @gregbunce has the data gone live yet?

**Comment by gregbunce** [comment]
Not yet. I'm guessing these evening.  I'm watching it.

**Comment by gregbunce** [comment]
Yup. Good point on the dates.

**Comment by gregbunce** [comment]
i checked the links for the updated date commits and everything looks/works as expected.  i'm going to merge.

**Comment by gregbunce** [comment]
@stdavis or @stdavis looks like i need one more approval on this one (i pushed a new commit).  i updated the URL and post dates to reflect today.  other than that, everything is the same.   thx!

**Review by steveoh — APPROVED** [review]

**Pull request merged**
