### PR TITLE
First scripted replace of ftp data links with drive links

### PR DESCRIPTION
**Pull request by keatonwalker**
Pull request description
------------------------
I ran the script to replace ftp links with drive links on one file. 

This one could use a more thorough check to make sure the links work and that re-writing the html file didn't hurt anything.

### CODE REVIEW

**Comment by steveoh** [comment]
It looks like your links worked but there are some broken or unshared links on that page to the data model.

image

**Comment by keatonwalker** [comment]
I fixed the data model link.

**Comment by steveoh** [comment]
nice, that same link is in there one more time and there is one to the trailheads as well with the sam issue. Can you get those two and then I can merge.

**Comment by stdavis** [comment]
@keatonwalker: Do you have the master list of all of the packages that your script is updating? I'd like to see if the ones that forklift builds are in there and remove them from forklift.

**Pull request merged**
