### PR TITLE
add road-update post sept2023

### PR DESCRIPTION
**Pull request by gregbunce**
and update dates for ng911 and network datasets

### CODE REVIEW

**Comment by gregbunce** [comment]
Three new addresses from this road update: 

- 1500 W 2600 S, Logan 84321

- 567 N 170 E, Providence 84321

- 575 E LONGVIEW DR, Elk Ridge 84651

**Comment by gregbunce** [comment]
it looks good to me.  let me know if i missed anything, else please approve and merge at your convince. thx.

**Review by steveoh — APPROVED** [review]

**Comment by steveoh** [comment]
> Three new addresses from this road update:
> 
> * 1500 W 2600 S, Logan 84321
> * 567 N 170 E, Providence 84321
> * 575 E LONGVIEW DR, Elk Ridge 84651

Did road grinder push these out yet?

**Comment by gregbunce** [comment]
strange: 
the api explorer can't find '575 E LONGVIEW DR, Elk Ridge 84651'

however, masquerade does:

image

**Comment by steveoh** [comment]
Masquerade is doing a test search in address points. The api is using the road grinder data. I'll dig into the api parts next week

**Comment by gregbunce** [comment]
just to close this conversation out.  Steve did some digging and discovered that the issue resides in the road centerlines data.  we have some inconsistencies in there in the casing of values in the address system/grid fields.  the API locator requires upper case, yet we have some records with title case in the data.  I will fix the issue by updating roadgrinder to ensure upper for address system/grid values.

**Pull request merged**
