### PR TITLE
Poverty blogpost

### PR DESCRIPTION
**Pull request by gregbunce**
draft pr to see what everything looks like.  @brigsz let me know what you think.
https://deploy-preview-1657--gis-utah-gov.netlify.app/intergenerational-poverty/

### CODE REVIEW

**Comment by gregbunce** [comment]
i'm done, it's ready for review.

**Comment by gregbunce** [comment]
note: the iframe worked fine, but i decided to show an image that links out to the interactive map.  

essentially, the text we added to the interactive map made the blog post appear too complicated.

**Review by stdavis — DISMISSED** [review]
Excellent work as always, Mr. Bunce.

**Comment by gregbunce** [comment]
thanks, mr davis!  you're very kind.

**Comment by stdavis** [comment]
Looks like I broke your link. I'll fix it and then merge...

**Review by stdavis — APPROVED** [review]

**Pull request merged**
