### PR TITLE
new fema hq lidar page

### PR DESCRIPTION
**Pull request by rkelson**

### CODE REVIEW

**Comment by rkelson** [comment]
I still need to create and add the .png files

**Review by steveoh — APPROVED** [review]
I suggest creating a new blog post to create a notification that the 2019 and 2020 products are available. As it is now, no one will know about this accomplishment. It seems worth knocking on some doors about.

**Comment by rkelson** [comment]
yeah maybe one day but not today. The majority of the '19 and '20 projects were completed a couple years ago. This is just the 2020 USGS piece.

**Comment by steveoh** [comment]
Ok, I'll get a tweet out.

**Pull request merged**
