### PR TITLE
Remove time sensitive blog posts

### PR DESCRIPTION
**Pull request by steveoh**
These blog posts were determined to no longer be relevant. Most were time sensitive updates. Some were found to have relevant information that should be extracted into a more permanent location.

You can view the actions and notes in the [blog post sorting](https://docs.google.com/spreadsheets/d/12GBuHLsfshgvORHmtczdY-OqmOWVEZbM_7SqpzjblYE/edit#gid=0) google sheet.

Review this and the sheet to see if you have any objections. 

We chose to keep 

- 1 year of road update blog posts
- 1 historical annual annexation recap + the current year quarterly updates

Thanks!

## Todo's

- [x] fix build with referenced links
- [x] remove all referenced images

### CODE REVIEW

**Comment by rkelson** [comment]
we can unpublish line 174 2016-08-29-2016-utah-lidar-acquisition.md

**Review by stdavis — DISMISSED** [review]
That was a long walk down memory lane.

**Comment by steveoh** [comment]
> we can unpublish line 174 2016-08-29-2016-utah-lidar-acquisition.md

it is unpublished.

**Review by nathankota — DISMISSED** [review]
Officially approving our triage of all the blog posts today.

**Comment by rkelson** [comment]
> > we can unpublish line 174 2016-08-29-2016-utah-lidar-acquisition.md
> 
> it is unpublished. Are you saying there is nothing of interest to move into the data pages etc?

yeah there is nothing worth saving. It's just like all the other _acquisition_ posts marked as unpublish

**Review by rkelson — APPROVED** [review]
looks good to me

**Comment by jacobdadams** [comment]
I agree with everything except removing the last GPS outage post. I think it's important to keep recent announcements like that so that someone can go back and reference them if needed. I can see discussions still occurring about recent events.

**Comment by steveoh** [comment]
> I think it's important to keep recent announcements like that so that someone can go back and reference them if needed. 

At what point do you remove it?

**Comment by jacobdadams** [comment]
> 
> At what point do you remove it?

I think the same one year rule as the other stuff for consistency's sake. Though, I could probably be convinced to do six months.

**Comment by steveoh** [comment]
Ok let's brake the internet!

**Pull request merged**
