### PR TITLE
add higher education section to schools page

### PR DESCRIPTION
**Pull request by gregbunce**

### CODE REVIEW

**Comment by steveoh** [comment]
first glance looks good. I'm wondering if we want to put the open sgid table name in the code block rather than the internal db table name. thoughts?

**Comment by gregbunce** [comment]
@ZachBeck see what you think.  it's pretty basic, but i think it covers the info (?).  feel free to add any needed info
https://deploy-preview-1496--gis-utah-gov.netlify.app/data/society/schools-libraries/

**Comment by gregbunce** [comment]
@steveoh yup, i thought the same thing.  i like it.  the internal name is meaningless to anyone outside the office.  i can make that change to the k to 12, too.

**Comment by ZachBeck** [comment]
I think it will work. I'm not worried about internal vs open sgid naming conventions, I think folks will find it either way.

**Comment by gregbunce** [comment]
@steveoh  I have some inconsistent spacing between the two schools grid package divs.  two spaces the kto12 div vs 4 spaces in the higher ed div.  what's the preferred spacing for gis.utah.gov?

**Comment by gregbunce** [comment]
seems like the website is mainly 2 spacing but vscode keeps defaulting me to 4.

**Comment by gregbunce** [comment]
should i shift the 4-space indentation to 2-space before I click "Read for review"?

**Review by steveoh — APPROVED** [review]

**Pull request merged**
